### ISSUE TITLE
TypeError: Object #<Socket> has no method 'clearLine'

### ISSUE THREAD

**Issue by DenisGorbachev** [arunoda/nodemiral#17]
```
failed: [prod.backuphamster.com] => {"changed": true, "cmd": "mup deploy > /tmp/mup.out", "delta": "0:00:44.002631", "end": "2015-09-17 15:59:53.860880", "rc": 8, "start": "2015-09-17 15:59:09.858249", "warnings": []}
stderr: 
/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168
    this.stream.clearLine();
                ^
TypeError: Object #<Socket> has no method 'clearLine'
    at ProgressBar.terminate (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168:17)
    at ProgressBar.tick (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:91:10)
    at ProgressBar.update (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:157:8)
    at Object.putFileOptions.onProgress (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:119:13)
    at sendProgressInfo (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/ssh.js:56:17)
    at writeCb (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1026:23)
    at state.requests.(anonymous function).cb (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:933:15)
    at SFTPStream._transform (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:374:17)
    at SFTPStream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SFTPStream._read (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:173:15)
    at SFTPStream.Transform._write (_stream_transform.js:167:12)

```

... when launching MUP with Ansible. That happens because Ansible doesn't create a TTY; instead, it executes `mup deploy` via `/bin/sh`.

The suggested fix is pretty simple: https://github.com/sindresorhus/grunt-shell/issues/77#issuecomment-53403019 + https://github.com/ember-cli/ember-cli/commit/4feedbe6d84d30701b473377fab9e99b62c476a6. However, I've noticed that nodemiral uses node-progress under the hood, and the error originates there. Maybe it's possible to skip using node-progress if stdout is not a TTY?

**Comment by arunoda** [comment]
Seems like that's the case.
Could you edit this file here: https://github.com/arunoda/nodemiral/blob/master/lib/session.js#L109

And send me a PR :)
